name: release-tag

on:
  repository_dispatch:
    types: [ metanorma/sts2mn ]

jobs:
  prepare:
    uses: metanorma/ci/.github/workflows/prepare-rake.yml@main

  tag-repo:
    runs-on: ubuntu-latest
    needs: prepare
    if: startsWith(github.event.client_payload.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.METANORMA_CI_PAT_TOKEN }}

      - run: |
          git config --global user.name "metanorma-ci"
          git config --global user.email "metanorma-ci@users.noreply.github.com"

      - name: Parse sts2mn version
        env:
          sts2mn_TAG: ${{ github.event.client_payload.ref }}
        run: echo sts2mn_VERSION=${sts2mn_TAG#*/v} >> ${GITHUB_ENV}

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ needs.prepare.outputs.default-ruby-version }}
          bundler-cache: true

      - run: rm -f bin/sts2mn.jar

      - run: bundle exec rake

      - run: |
          gem install gem-release
          gem bump --version ${sts2mn_VERSION} --no-commit

      - name: Push commit and tag
        run: |
          git add -u bin/sts2mn.jar lib/sts2mn/version.rb
          git commit -m "Bump version to ${sts2mn_VERSION}"
          git tag v${sts2mn_VERSION}
          git push github HEAD:${GITHUB_REF} --tags

      - if: failure()
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.METANORMA_CI_PAT_TOKEN }}
        with:
          assignees: CAMOBAP
          update_existing: true
          search_existing: all
